AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - "*.gemspec"
    - "vendor/**/*"
    - "lib/**/*.tab.rb"
    - "lib/tecsgen.rb"
    - "lib/tecsgen/**/*.rb"
    - "glade/*.rb"

Layout/ExtraSpacing:
  AllowForAlignment: true
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/UnderscorePrefixedVariableName:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false

Metrics/LineLength:
  Enabled: false
Metrics/ClassLength:
  Exclude:
    - "test/**/*.rb"
Metrics/ParameterLists:
  Max: 7
Metrics/MethodLength:
  Max: 30

Naming/FileName:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - x
    - y
    - x0
    - y0
    - xm
    - ym
    - xx
    - xy
    - yx
    - yy

Style/AsciiComments:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - "**/*.rake"
    - "Rakefile"
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/BarePercentLiterals:
  EnforcedStyle: percent_q
Style/BracesAroundHashParameters:
  Enabled: false
Style/PercentQLiterals:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
